export default  {
    ADD_CHANNEL: 'ADD_CHANNEL',
    DELETE_CHANNEL: 'DELETE_CHANNEL',
    UPDATE_FAVORITES: 'UPDATE_FAVORITES',

    IS_FAVORITED: 'IS_FAVORITED',
    IS_NOT_FAVORITED: 'IS_NOT_FAVORITED'
}