export default  {
    ADD_CHANNEL: 'ADD_CHANNEL',
    DELETE_CHANNEL: 'DELETE_CHANNEL',
    UPDATE_FAVORITES: 'UPDATE_FAVORITES',

    USER_LOADED: 'USER_LOADED',
    USER_LOADING: 'USER_LOADING',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    GET_ERRORS: 'GET_ERROR',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
}